name: Swift Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Swift tests
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Show Swift version
        run: swift --version

      - name: Run tests
        run: swift test -Xswiftc -target -Xswiftc "$(uname -m)-apple-macosx10.15"

      - name: Build for iOS
        run: xcodebuild -scheme AppIconChanger -destination 'generic/platform=iOS' build
